// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: api.proto

package com.mh.flux.api;

public final class FluxAPIProto {
  private FluxAPIProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_topupRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_topupRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_topupRequest_payloadBody_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_topupRequest_payloadBody_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_topupResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_topupResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_topupResponse_payloadBody_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_topupResponse_payloadBody_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_queryResultRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_queryResultRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_queryResultRequest_payloadBody_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_queryResultRequest_payloadBody_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_queryResultResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_queryResultResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_queryResultResponse_payloadBody_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_queryResultResponse_payloadBody_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_queryBalanceRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_queryBalanceRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_queryBalanceRequest_payloadBody_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_queryBalanceRequest_payloadBody_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_queryBalanceResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_queryBalanceResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_queryBalanceResponse_payloadBody_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_queryBalanceResponse_payloadBody_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\tapi.proto\032\031commonRequestHeader.proto\032\032" +
      "commonResponseHeader.proto\"\354\001\n\014topupRequ" +
      "est\022\032\n\006header\030\001 \001(\0132\n.reqHeader\022*\n\007paylo" +
      "ad\030\002 \001(\0132\031.topupRequest.payloadBody\032\223\001\n\013" +
      "payloadBody\022\014\n\004user\030\001 \001(\t\022\r\n\005scope\030\002 \001(\005" +
      "\022\017\n\007orderno\030\003 \001(\t\022\016\n\006mobile\030\004 \001(\t\022\022\n\nact" +
      "iveflag\030\005 \001(\005\022\022\n\nexpiration\030\006 \001(\005\022\017\n\007flu" +
      "xnum\030\007 \001(\005\022\r\n\005pcode\030\010 \001(\t\"y\n\rtopupRespon" +
      "se\022\033\n\006header\030\001 \001(\0132\013.respHeader\022+\n\007paylo" +
      "ad\030\002 \001(\0132\032.topupResponse.payloadBody\032\036\n\013",
      "payloadBody\022\017\n\007orderid\030\001 \001(\t\"\202\001\n\022queryRe" +
      "sultRequest\022\032\n\006header\030\001 \001(\0132\n.reqHeader\022" +
      "0\n\007payload\030\002 \001(\0132\037.queryResultRequest.pa" +
      "yloadBody\032\036\n\013payloadBody\022\017\n\007orderid\030\001 \001(" +
      "\t\"\222\001\n\023queryResultResponse\022\033\n\006header\030\001 \001(" +
      "\0132\013.respHeader\0221\n\007payload\030\002 \001(\0132 .queryR" +
      "esultResponse.payloadBody\032+\n\013payloadBody" +
      "\022\016\n\006result\030\001 \001(\005\022\014\n\004desc\030\002 \001(\t\"\201\001\n\023query" +
      "BalanceRequest\022\032\n\006header\030\001 \001(\0132\n.reqHead" +
      "er\0221\n\007payload\030\002 \001(\0132 .queryBalanceReques",
      "t.payloadBody\032\033\n\013payloadBody\022\014\n\004user\030\001 \001" +
      "(\t\"\231\001\n\024queryBalanceResponse\022\033\n\006header\030\001 " +
      "\001(\0132\013.respHeader\0222\n\007payload\030\002 \001(\0132!.quer" +
      "yBalanceResponse.payloadBody\0320\n\013payloadB" +
      "ody\022\017\n\007balance\030\001 \001(\t\022\020\n\010currency\030\002 \001(\t2\263" +
      "\001\n\014topupService\022(\n\005topup\022\r.topupRequest\032" +
      "\016.topupResponse\"\000\022=\n\014queryBalance\022\024.quer" +
      "yBalanceRequest\032\025.queryBalanceResponse\"\000" +
      "\022:\n\013queryResult\022\023.queryResultRequest\032\024.q" +
      "ueryResultResponse\"\000B(\n\017com.mh.flux.apiB",
      "\014FluxAPIProtoP\001\242\002\004FLUXb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.mh.flux.api.request.FluxAPIProto.getDescriptor(),
          com.mh.flux.api.response.FluxAPIProto.getDescriptor(),
        }, assigner);
    internal_static_topupRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_topupRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_topupRequest_descriptor,
        new java.lang.String[] { "Header", "Payload", });
    internal_static_topupRequest_payloadBody_descriptor =
      internal_static_topupRequest_descriptor.getNestedTypes().get(0);
    internal_static_topupRequest_payloadBody_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_topupRequest_payloadBody_descriptor,
        new java.lang.String[] { "User", "Scope", "Orderno", "Mobile", "Activeflag", "Expiration", "Fluxnum", "Pcode", });
    internal_static_topupResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_topupResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_topupResponse_descriptor,
        new java.lang.String[] { "Header", "Payload", });
    internal_static_topupResponse_payloadBody_descriptor =
      internal_static_topupResponse_descriptor.getNestedTypes().get(0);
    internal_static_topupResponse_payloadBody_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_topupResponse_payloadBody_descriptor,
        new java.lang.String[] { "Orderid", });
    internal_static_queryResultRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_queryResultRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_queryResultRequest_descriptor,
        new java.lang.String[] { "Header", "Payload", });
    internal_static_queryResultRequest_payloadBody_descriptor =
      internal_static_queryResultRequest_descriptor.getNestedTypes().get(0);
    internal_static_queryResultRequest_payloadBody_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_queryResultRequest_payloadBody_descriptor,
        new java.lang.String[] { "Orderid", });
    internal_static_queryResultResponse_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_queryResultResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_queryResultResponse_descriptor,
        new java.lang.String[] { "Header", "Payload", });
    internal_static_queryResultResponse_payloadBody_descriptor =
      internal_static_queryResultResponse_descriptor.getNestedTypes().get(0);
    internal_static_queryResultResponse_payloadBody_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_queryResultResponse_payloadBody_descriptor,
        new java.lang.String[] { "Result", "Desc", });
    internal_static_queryBalanceRequest_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_queryBalanceRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_queryBalanceRequest_descriptor,
        new java.lang.String[] { "Header", "Payload", });
    internal_static_queryBalanceRequest_payloadBody_descriptor =
      internal_static_queryBalanceRequest_descriptor.getNestedTypes().get(0);
    internal_static_queryBalanceRequest_payloadBody_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_queryBalanceRequest_payloadBody_descriptor,
        new java.lang.String[] { "User", });
    internal_static_queryBalanceResponse_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_queryBalanceResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_queryBalanceResponse_descriptor,
        new java.lang.String[] { "Header", "Payload", });
    internal_static_queryBalanceResponse_payloadBody_descriptor =
      internal_static_queryBalanceResponse_descriptor.getNestedTypes().get(0);
    internal_static_queryBalanceResponse_payloadBody_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_queryBalanceResponse_payloadBody_descriptor,
        new java.lang.String[] { "Balance", "Currency", });
    com.mh.flux.api.request.FluxAPIProto.getDescriptor();
    com.mh.flux.api.response.FluxAPIProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
