// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: api.proto

package com.mh.flux.api;

public interface queryResultRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:queryResultRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional .reqHeader header = 1;</code>
   */
  boolean hasHeader();
  /**
   * <code>optional .reqHeader header = 1;</code>
   */
  com.mh.flux.api.request.reqHeader getHeader();
  /**
   * <code>optional .reqHeader header = 1;</code>
   */
  com.mh.flux.api.request.reqHeaderOrBuilder getHeaderOrBuilder();

  /**
   * <code>optional .queryResultRequest.payloadBody payload = 2;</code>
   */
  boolean hasPayload();
  /**
   * <code>optional .queryResultRequest.payloadBody payload = 2;</code>
   */
  com.mh.flux.api.queryResultRequest.payloadBody getPayload();
  /**
   * <code>optional .queryResultRequest.payloadBody payload = 2;</code>
   */
  com.mh.flux.api.queryResultRequest.payloadBodyOrBuilder getPayloadOrBuilder();
}
