// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: api.proto

package com.mh.flux.api;

public interface topupResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:topupResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional .respHeader header = 1;</code>
   */
  boolean hasHeader();
  /**
   * <code>optional .respHeader header = 1;</code>
   */
  com.mh.flux.api.response.respHeader getHeader();
  /**
   * <code>optional .respHeader header = 1;</code>
   */
  com.mh.flux.api.response.respHeaderOrBuilder getHeaderOrBuilder();

  /**
   * <code>optional .topupResponse.payloadBody payload = 2;</code>
   */
  boolean hasPayload();
  /**
   * <code>optional .topupResponse.payloadBody payload = 2;</code>
   */
  com.mh.flux.api.topupResponse.payloadBody getPayload();
  /**
   * <code>optional .topupResponse.payloadBody payload = 2;</code>
   */
  com.mh.flux.api.topupResponse.payloadBodyOrBuilder getPayloadOrBuilder();
}
