// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: api.proto

package com.mh.flux.api;

/**
 * Protobuf type {@code topupRequest}
 */
public  final class topupRequest extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:topupRequest)
    topupRequestOrBuilder {
  // Use topupRequest.newBuilder() to construct.
  private topupRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private topupRequest() {
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
  }
  private topupRequest(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    int mutable_bitField0_ = 0;
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!input.skipField(tag)) {
              done = true;
            }
            break;
          }
          case 10: {
            com.mh.flux.api.request.reqHeader.Builder subBuilder = null;
            if (header_ != null) {
              subBuilder = header_.toBuilder();
            }
            header_ = input.readMessage(com.mh.flux.api.request.reqHeader.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(header_);
              header_ = subBuilder.buildPartial();
            }

            break;
          }
          case 18: {
            com.mh.flux.api.topupRequest.payloadBody.Builder subBuilder = null;
            if (payload_ != null) {
              subBuilder = payload_.toBuilder();
            }
            payload_ = input.readMessage(com.mh.flux.api.topupRequest.payloadBody.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(payload_);
              payload_ = subBuilder.buildPartial();
            }

            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.mh.flux.api.FluxAPIProto.internal_static_topupRequest_descriptor;
  }

  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.mh.flux.api.FluxAPIProto.internal_static_topupRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.mh.flux.api.topupRequest.class, com.mh.flux.api.topupRequest.Builder.class);
  }

  public interface payloadBodyOrBuilder extends
      // @@protoc_insertion_point(interface_extends:topupRequest.payloadBody)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional string user = 1;</code>
     */
    java.lang.String getUser();
    /**
     * <code>optional string user = 1;</code>
     */
    com.google.protobuf.ByteString
        getUserBytes();

    /**
     * <code>optional int32 scope = 2;</code>
     */
    int getScope();

    /**
     * <code>optional string orderno = 3;</code>
     */
    java.lang.String getOrderno();
    /**
     * <code>optional string orderno = 3;</code>
     */
    com.google.protobuf.ByteString
        getOrdernoBytes();

    /**
     * <code>optional string mobile = 4;</code>
     */
    java.lang.String getMobile();
    /**
     * <code>optional string mobile = 4;</code>
     */
    com.google.protobuf.ByteString
        getMobileBytes();

    /**
     * <code>optional int32 activeflag = 5;</code>
     */
    int getActiveflag();

    /**
     * <code>optional int32 expiration = 6;</code>
     */
    int getExpiration();

    /**
     * <code>optional int32 fluxnum = 7;</code>
     */
    int getFluxnum();

    /**
     * <code>optional string pcode = 8;</code>
     */
    java.lang.String getPcode();
    /**
     * <code>optional string pcode = 8;</code>
     */
    com.google.protobuf.ByteString
        getPcodeBytes();
  }
  /**
   * Protobuf type {@code topupRequest.payloadBody}
   */
  public  static final class payloadBody extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:topupRequest.payloadBody)
      payloadBodyOrBuilder {
    // Use payloadBody.newBuilder() to construct.
    private payloadBody(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private payloadBody() {
      user_ = "";
      scope_ = 0;
      orderno_ = "";
      mobile_ = "";
      activeflag_ = 0;
      expiration_ = 0;
      fluxnum_ = 0;
      pcode_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private payloadBody(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              user_ = s;
              break;
            }
            case 16: {

              scope_ = input.readInt32();
              break;
            }
            case 26: {
              java.lang.String s = input.readStringRequireUtf8();

              orderno_ = s;
              break;
            }
            case 34: {
              java.lang.String s = input.readStringRequireUtf8();

              mobile_ = s;
              break;
            }
            case 40: {

              activeflag_ = input.readInt32();
              break;
            }
            case 48: {

              expiration_ = input.readInt32();
              break;
            }
            case 56: {

              fluxnum_ = input.readInt32();
              break;
            }
            case 66: {
              java.lang.String s = input.readStringRequireUtf8();

              pcode_ = s;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.mh.flux.api.FluxAPIProto.internal_static_topupRequest_payloadBody_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.mh.flux.api.FluxAPIProto.internal_static_topupRequest_payloadBody_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.mh.flux.api.topupRequest.payloadBody.class, com.mh.flux.api.topupRequest.payloadBody.Builder.class);
    }

    public static final int USER_FIELD_NUMBER = 1;
    private volatile java.lang.Object user_;
    /**
     * <code>optional string user = 1;</code>
     */
    public java.lang.String getUser() {
      java.lang.Object ref = user_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        user_ = s;
        return s;
      }
    }
    /**
     * <code>optional string user = 1;</code>
     */
    public com.google.protobuf.ByteString
        getUserBytes() {
      java.lang.Object ref = user_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        user_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int SCOPE_FIELD_NUMBER = 2;
    private int scope_;
    /**
     * <code>optional int32 scope = 2;</code>
     */
    public int getScope() {
      return scope_;
    }

    public static final int ORDERNO_FIELD_NUMBER = 3;
    private volatile java.lang.Object orderno_;
    /**
     * <code>optional string orderno = 3;</code>
     */
    public java.lang.String getOrderno() {
      java.lang.Object ref = orderno_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        orderno_ = s;
        return s;
      }
    }
    /**
     * <code>optional string orderno = 3;</code>
     */
    public com.google.protobuf.ByteString
        getOrdernoBytes() {
      java.lang.Object ref = orderno_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        orderno_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int MOBILE_FIELD_NUMBER = 4;
    private volatile java.lang.Object mobile_;
    /**
     * <code>optional string mobile = 4;</code>
     */
    public java.lang.String getMobile() {
      java.lang.Object ref = mobile_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        mobile_ = s;
        return s;
      }
    }
    /**
     * <code>optional string mobile = 4;</code>
     */
    public com.google.protobuf.ByteString
        getMobileBytes() {
      java.lang.Object ref = mobile_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        mobile_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int ACTIVEFLAG_FIELD_NUMBER = 5;
    private int activeflag_;
    /**
     * <code>optional int32 activeflag = 5;</code>
     */
    public int getActiveflag() {
      return activeflag_;
    }

    public static final int EXPIRATION_FIELD_NUMBER = 6;
    private int expiration_;
    /**
     * <code>optional int32 expiration = 6;</code>
     */
    public int getExpiration() {
      return expiration_;
    }

    public static final int FLUXNUM_FIELD_NUMBER = 7;
    private int fluxnum_;
    /**
     * <code>optional int32 fluxnum = 7;</code>
     */
    public int getFluxnum() {
      return fluxnum_;
    }

    public static final int PCODE_FIELD_NUMBER = 8;
    private volatile java.lang.Object pcode_;
    /**
     * <code>optional string pcode = 8;</code>
     */
    public java.lang.String getPcode() {
      java.lang.Object ref = pcode_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        pcode_ = s;
        return s;
      }
    }
    /**
     * <code>optional string pcode = 8;</code>
     */
    public com.google.protobuf.ByteString
        getPcodeBytes() {
      java.lang.Object ref = pcode_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        pcode_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getUserBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, user_);
      }
      if (scope_ != 0) {
        output.writeInt32(2, scope_);
      }
      if (!getOrdernoBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, orderno_);
      }
      if (!getMobileBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, mobile_);
      }
      if (activeflag_ != 0) {
        output.writeInt32(5, activeflag_);
      }
      if (expiration_ != 0) {
        output.writeInt32(6, expiration_);
      }
      if (fluxnum_ != 0) {
        output.writeInt32(7, fluxnum_);
      }
      if (!getPcodeBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 8, pcode_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getUserBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, user_);
      }
      if (scope_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, scope_);
      }
      if (!getOrdernoBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, orderno_);
      }
      if (!getMobileBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, mobile_);
      }
      if (activeflag_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(5, activeflag_);
      }
      if (expiration_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(6, expiration_);
      }
      if (fluxnum_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(7, fluxnum_);
      }
      if (!getPcodeBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(8, pcode_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.mh.flux.api.topupRequest.payloadBody)) {
        return super.equals(obj);
      }
      com.mh.flux.api.topupRequest.payloadBody other = (com.mh.flux.api.topupRequest.payloadBody) obj;

      boolean result = true;
      result = result && getUser()
          .equals(other.getUser());
      result = result && (getScope()
          == other.getScope());
      result = result && getOrderno()
          .equals(other.getOrderno());
      result = result && getMobile()
          .equals(other.getMobile());
      result = result && (getActiveflag()
          == other.getActiveflag());
      result = result && (getExpiration()
          == other.getExpiration());
      result = result && (getFluxnum()
          == other.getFluxnum());
      result = result && getPcode()
          .equals(other.getPcode());
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      hash = (37 * hash) + USER_FIELD_NUMBER;
      hash = (53 * hash) + getUser().hashCode();
      hash = (37 * hash) + SCOPE_FIELD_NUMBER;
      hash = (53 * hash) + getScope();
      hash = (37 * hash) + ORDERNO_FIELD_NUMBER;
      hash = (53 * hash) + getOrderno().hashCode();
      hash = (37 * hash) + MOBILE_FIELD_NUMBER;
      hash = (53 * hash) + getMobile().hashCode();
      hash = (37 * hash) + ACTIVEFLAG_FIELD_NUMBER;
      hash = (53 * hash) + getActiveflag();
      hash = (37 * hash) + EXPIRATION_FIELD_NUMBER;
      hash = (53 * hash) + getExpiration();
      hash = (37 * hash) + FLUXNUM_FIELD_NUMBER;
      hash = (53 * hash) + getFluxnum();
      hash = (37 * hash) + PCODE_FIELD_NUMBER;
      hash = (53 * hash) + getPcode().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.mh.flux.api.topupRequest.payloadBody parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.mh.flux.api.topupRequest.payloadBody parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.mh.flux.api.topupRequest.payloadBody parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.mh.flux.api.topupRequest.payloadBody parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.mh.flux.api.topupRequest.payloadBody parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.mh.flux.api.topupRequest.payloadBody parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.mh.flux.api.topupRequest.payloadBody parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.mh.flux.api.topupRequest.payloadBody parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.mh.flux.api.topupRequest.payloadBody parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.mh.flux.api.topupRequest.payloadBody parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.mh.flux.api.topupRequest.payloadBody prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code topupRequest.payloadBody}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:topupRequest.payloadBody)
        com.mh.flux.api.topupRequest.payloadBodyOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.mh.flux.api.FluxAPIProto.internal_static_topupRequest_payloadBody_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.mh.flux.api.FluxAPIProto.internal_static_topupRequest_payloadBody_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.mh.flux.api.topupRequest.payloadBody.class, com.mh.flux.api.topupRequest.payloadBody.Builder.class);
      }

      // Construct using com.mh.flux.api.topupRequest.payloadBody.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        user_ = "";

        scope_ = 0;

        orderno_ = "";

        mobile_ = "";

        activeflag_ = 0;

        expiration_ = 0;

        fluxnum_ = 0;

        pcode_ = "";

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.mh.flux.api.FluxAPIProto.internal_static_topupRequest_payloadBody_descriptor;
      }

      public com.mh.flux.api.topupRequest.payloadBody getDefaultInstanceForType() {
        return com.mh.flux.api.topupRequest.payloadBody.getDefaultInstance();
      }

      public com.mh.flux.api.topupRequest.payloadBody build() {
        com.mh.flux.api.topupRequest.payloadBody result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.mh.flux.api.topupRequest.payloadBody buildPartial() {
        com.mh.flux.api.topupRequest.payloadBody result = new com.mh.flux.api.topupRequest.payloadBody(this);
        result.user_ = user_;
        result.scope_ = scope_;
        result.orderno_ = orderno_;
        result.mobile_ = mobile_;
        result.activeflag_ = activeflag_;
        result.expiration_ = expiration_;
        result.fluxnum_ = fluxnum_;
        result.pcode_ = pcode_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.mh.flux.api.topupRequest.payloadBody) {
          return mergeFrom((com.mh.flux.api.topupRequest.payloadBody)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.mh.flux.api.topupRequest.payloadBody other) {
        if (other == com.mh.flux.api.topupRequest.payloadBody.getDefaultInstance()) return this;
        if (!other.getUser().isEmpty()) {
          user_ = other.user_;
          onChanged();
        }
        if (other.getScope() != 0) {
          setScope(other.getScope());
        }
        if (!other.getOrderno().isEmpty()) {
          orderno_ = other.orderno_;
          onChanged();
        }
        if (!other.getMobile().isEmpty()) {
          mobile_ = other.mobile_;
          onChanged();
        }
        if (other.getActiveflag() != 0) {
          setActiveflag(other.getActiveflag());
        }
        if (other.getExpiration() != 0) {
          setExpiration(other.getExpiration());
        }
        if (other.getFluxnum() != 0) {
          setFluxnum(other.getFluxnum());
        }
        if (!other.getPcode().isEmpty()) {
          pcode_ = other.pcode_;
          onChanged();
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.mh.flux.api.topupRequest.payloadBody parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.mh.flux.api.topupRequest.payloadBody) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object user_ = "";
      /**
       * <code>optional string user = 1;</code>
       */
      public java.lang.String getUser() {
        java.lang.Object ref = user_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          user_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string user = 1;</code>
       */
      public com.google.protobuf.ByteString
          getUserBytes() {
        java.lang.Object ref = user_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          user_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string user = 1;</code>
       */
      public Builder setUser(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        user_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string user = 1;</code>
       */
      public Builder clearUser() {
        
        user_ = getDefaultInstance().getUser();
        onChanged();
        return this;
      }
      /**
       * <code>optional string user = 1;</code>
       */
      public Builder setUserBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        user_ = value;
        onChanged();
        return this;
      }

      private int scope_ ;
      /**
       * <code>optional int32 scope = 2;</code>
       */
      public int getScope() {
        return scope_;
      }
      /**
       * <code>optional int32 scope = 2;</code>
       */
      public Builder setScope(int value) {
        
        scope_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 scope = 2;</code>
       */
      public Builder clearScope() {
        
        scope_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object orderno_ = "";
      /**
       * <code>optional string orderno = 3;</code>
       */
      public java.lang.String getOrderno() {
        java.lang.Object ref = orderno_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          orderno_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string orderno = 3;</code>
       */
      public com.google.protobuf.ByteString
          getOrdernoBytes() {
        java.lang.Object ref = orderno_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          orderno_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string orderno = 3;</code>
       */
      public Builder setOrderno(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        orderno_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string orderno = 3;</code>
       */
      public Builder clearOrderno() {
        
        orderno_ = getDefaultInstance().getOrderno();
        onChanged();
        return this;
      }
      /**
       * <code>optional string orderno = 3;</code>
       */
      public Builder setOrdernoBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        orderno_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object mobile_ = "";
      /**
       * <code>optional string mobile = 4;</code>
       */
      public java.lang.String getMobile() {
        java.lang.Object ref = mobile_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          mobile_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string mobile = 4;</code>
       */
      public com.google.protobuf.ByteString
          getMobileBytes() {
        java.lang.Object ref = mobile_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          mobile_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string mobile = 4;</code>
       */
      public Builder setMobile(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        mobile_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string mobile = 4;</code>
       */
      public Builder clearMobile() {
        
        mobile_ = getDefaultInstance().getMobile();
        onChanged();
        return this;
      }
      /**
       * <code>optional string mobile = 4;</code>
       */
      public Builder setMobileBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        mobile_ = value;
        onChanged();
        return this;
      }

      private int activeflag_ ;
      /**
       * <code>optional int32 activeflag = 5;</code>
       */
      public int getActiveflag() {
        return activeflag_;
      }
      /**
       * <code>optional int32 activeflag = 5;</code>
       */
      public Builder setActiveflag(int value) {
        
        activeflag_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 activeflag = 5;</code>
       */
      public Builder clearActiveflag() {
        
        activeflag_ = 0;
        onChanged();
        return this;
      }

      private int expiration_ ;
      /**
       * <code>optional int32 expiration = 6;</code>
       */
      public int getExpiration() {
        return expiration_;
      }
      /**
       * <code>optional int32 expiration = 6;</code>
       */
      public Builder setExpiration(int value) {
        
        expiration_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 expiration = 6;</code>
       */
      public Builder clearExpiration() {
        
        expiration_ = 0;
        onChanged();
        return this;
      }

      private int fluxnum_ ;
      /**
       * <code>optional int32 fluxnum = 7;</code>
       */
      public int getFluxnum() {
        return fluxnum_;
      }
      /**
       * <code>optional int32 fluxnum = 7;</code>
       */
      public Builder setFluxnum(int value) {
        
        fluxnum_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 fluxnum = 7;</code>
       */
      public Builder clearFluxnum() {
        
        fluxnum_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object pcode_ = "";
      /**
       * <code>optional string pcode = 8;</code>
       */
      public java.lang.String getPcode() {
        java.lang.Object ref = pcode_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          pcode_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string pcode = 8;</code>
       */
      public com.google.protobuf.ByteString
          getPcodeBytes() {
        java.lang.Object ref = pcode_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          pcode_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string pcode = 8;</code>
       */
      public Builder setPcode(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        pcode_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string pcode = 8;</code>
       */
      public Builder clearPcode() {
        
        pcode_ = getDefaultInstance().getPcode();
        onChanged();
        return this;
      }
      /**
       * <code>optional string pcode = 8;</code>
       */
      public Builder setPcodeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        pcode_ = value;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:topupRequest.payloadBody)
    }

    // @@protoc_insertion_point(class_scope:topupRequest.payloadBody)
    private static final com.mh.flux.api.topupRequest.payloadBody DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.mh.flux.api.topupRequest.payloadBody();
    }

    public static com.mh.flux.api.topupRequest.payloadBody getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<payloadBody>
        PARSER = new com.google.protobuf.AbstractParser<payloadBody>() {
      public payloadBody parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new payloadBody(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<payloadBody> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<payloadBody> getParserForType() {
      return PARSER;
    }

    public com.mh.flux.api.topupRequest.payloadBody getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public static final int HEADER_FIELD_NUMBER = 1;
  private com.mh.flux.api.request.reqHeader header_;
  /**
   * <code>optional .reqHeader header = 1;</code>
   */
  public boolean hasHeader() {
    return header_ != null;
  }
  /**
   * <code>optional .reqHeader header = 1;</code>
   */
  public com.mh.flux.api.request.reqHeader getHeader() {
    return header_ == null ? com.mh.flux.api.request.reqHeader.getDefaultInstance() : header_;
  }
  /**
   * <code>optional .reqHeader header = 1;</code>
   */
  public com.mh.flux.api.request.reqHeaderOrBuilder getHeaderOrBuilder() {
    return getHeader();
  }

  public static final int PAYLOAD_FIELD_NUMBER = 2;
  private com.mh.flux.api.topupRequest.payloadBody payload_;
  /**
   * <code>optional .topupRequest.payloadBody payload = 2;</code>
   */
  public boolean hasPayload() {
    return payload_ != null;
  }
  /**
   * <code>optional .topupRequest.payloadBody payload = 2;</code>
   */
  public com.mh.flux.api.topupRequest.payloadBody getPayload() {
    return payload_ == null ? com.mh.flux.api.topupRequest.payloadBody.getDefaultInstance() : payload_;
  }
  /**
   * <code>optional .topupRequest.payloadBody payload = 2;</code>
   */
  public com.mh.flux.api.topupRequest.payloadBodyOrBuilder getPayloadOrBuilder() {
    return getPayload();
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (header_ != null) {
      output.writeMessage(1, getHeader());
    }
    if (payload_ != null) {
      output.writeMessage(2, getPayload());
    }
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (header_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, getHeader());
    }
    if (payload_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, getPayload());
    }
    memoizedSize = size;
    return size;
  }

  private static final long serialVersionUID = 0L;
  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.mh.flux.api.topupRequest)) {
      return super.equals(obj);
    }
    com.mh.flux.api.topupRequest other = (com.mh.flux.api.topupRequest) obj;

    boolean result = true;
    result = result && (hasHeader() == other.hasHeader());
    if (hasHeader()) {
      result = result && getHeader()
          .equals(other.getHeader());
    }
    result = result && (hasPayload() == other.hasPayload());
    if (hasPayload()) {
      result = result && getPayload()
          .equals(other.getPayload());
    }
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptorForType().hashCode();
    if (hasHeader()) {
      hash = (37 * hash) + HEADER_FIELD_NUMBER;
      hash = (53 * hash) + getHeader().hashCode();
    }
    if (hasPayload()) {
      hash = (37 * hash) + PAYLOAD_FIELD_NUMBER;
      hash = (53 * hash) + getPayload().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.mh.flux.api.topupRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.mh.flux.api.topupRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.mh.flux.api.topupRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.mh.flux.api.topupRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.mh.flux.api.topupRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.mh.flux.api.topupRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.mh.flux.api.topupRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.mh.flux.api.topupRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.mh.flux.api.topupRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.mh.flux.api.topupRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.mh.flux.api.topupRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code topupRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:topupRequest)
      com.mh.flux.api.topupRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.mh.flux.api.FluxAPIProto.internal_static_topupRequest_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.mh.flux.api.FluxAPIProto.internal_static_topupRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.mh.flux.api.topupRequest.class, com.mh.flux.api.topupRequest.Builder.class);
    }

    // Construct using com.mh.flux.api.topupRequest.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    public Builder clear() {
      super.clear();
      if (headerBuilder_ == null) {
        header_ = null;
      } else {
        header_ = null;
        headerBuilder_ = null;
      }
      if (payloadBuilder_ == null) {
        payload_ = null;
      } else {
        payload_ = null;
        payloadBuilder_ = null;
      }
      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.mh.flux.api.FluxAPIProto.internal_static_topupRequest_descriptor;
    }

    public com.mh.flux.api.topupRequest getDefaultInstanceForType() {
      return com.mh.flux.api.topupRequest.getDefaultInstance();
    }

    public com.mh.flux.api.topupRequest build() {
      com.mh.flux.api.topupRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public com.mh.flux.api.topupRequest buildPartial() {
      com.mh.flux.api.topupRequest result = new com.mh.flux.api.topupRequest(this);
      if (headerBuilder_ == null) {
        result.header_ = header_;
      } else {
        result.header_ = headerBuilder_.build();
      }
      if (payloadBuilder_ == null) {
        result.payload_ = payload_;
      } else {
        result.payload_ = payloadBuilder_.build();
      }
      onBuilt();
      return result;
    }

    public Builder clone() {
      return (Builder) super.clone();
    }
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.setField(field, value);
    }
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.mh.flux.api.topupRequest) {
        return mergeFrom((com.mh.flux.api.topupRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.mh.flux.api.topupRequest other) {
      if (other == com.mh.flux.api.topupRequest.getDefaultInstance()) return this;
      if (other.hasHeader()) {
        mergeHeader(other.getHeader());
      }
      if (other.hasPayload()) {
        mergePayload(other.getPayload());
      }
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.mh.flux.api.topupRequest parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.mh.flux.api.topupRequest) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private com.mh.flux.api.request.reqHeader header_ = null;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.mh.flux.api.request.reqHeader, com.mh.flux.api.request.reqHeader.Builder, com.mh.flux.api.request.reqHeaderOrBuilder> headerBuilder_;
    /**
     * <code>optional .reqHeader header = 1;</code>
     */
    public boolean hasHeader() {
      return headerBuilder_ != null || header_ != null;
    }
    /**
     * <code>optional .reqHeader header = 1;</code>
     */
    public com.mh.flux.api.request.reqHeader getHeader() {
      if (headerBuilder_ == null) {
        return header_ == null ? com.mh.flux.api.request.reqHeader.getDefaultInstance() : header_;
      } else {
        return headerBuilder_.getMessage();
      }
    }
    /**
     * <code>optional .reqHeader header = 1;</code>
     */
    public Builder setHeader(com.mh.flux.api.request.reqHeader value) {
      if (headerBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        header_ = value;
        onChanged();
      } else {
        headerBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>optional .reqHeader header = 1;</code>
     */
    public Builder setHeader(
        com.mh.flux.api.request.reqHeader.Builder builderForValue) {
      if (headerBuilder_ == null) {
        header_ = builderForValue.build();
        onChanged();
      } else {
        headerBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>optional .reqHeader header = 1;</code>
     */
    public Builder mergeHeader(com.mh.flux.api.request.reqHeader value) {
      if (headerBuilder_ == null) {
        if (header_ != null) {
          header_ =
            com.mh.flux.api.request.reqHeader.newBuilder(header_).mergeFrom(value).buildPartial();
        } else {
          header_ = value;
        }
        onChanged();
      } else {
        headerBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>optional .reqHeader header = 1;</code>
     */
    public Builder clearHeader() {
      if (headerBuilder_ == null) {
        header_ = null;
        onChanged();
      } else {
        header_ = null;
        headerBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>optional .reqHeader header = 1;</code>
     */
    public com.mh.flux.api.request.reqHeader.Builder getHeaderBuilder() {
      
      onChanged();
      return getHeaderFieldBuilder().getBuilder();
    }
    /**
     * <code>optional .reqHeader header = 1;</code>
     */
    public com.mh.flux.api.request.reqHeaderOrBuilder getHeaderOrBuilder() {
      if (headerBuilder_ != null) {
        return headerBuilder_.getMessageOrBuilder();
      } else {
        return header_ == null ?
            com.mh.flux.api.request.reqHeader.getDefaultInstance() : header_;
      }
    }
    /**
     * <code>optional .reqHeader header = 1;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.mh.flux.api.request.reqHeader, com.mh.flux.api.request.reqHeader.Builder, com.mh.flux.api.request.reqHeaderOrBuilder> 
        getHeaderFieldBuilder() {
      if (headerBuilder_ == null) {
        headerBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.mh.flux.api.request.reqHeader, com.mh.flux.api.request.reqHeader.Builder, com.mh.flux.api.request.reqHeaderOrBuilder>(
                getHeader(),
                getParentForChildren(),
                isClean());
        header_ = null;
      }
      return headerBuilder_;
    }

    private com.mh.flux.api.topupRequest.payloadBody payload_ = null;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.mh.flux.api.topupRequest.payloadBody, com.mh.flux.api.topupRequest.payloadBody.Builder, com.mh.flux.api.topupRequest.payloadBodyOrBuilder> payloadBuilder_;
    /**
     * <code>optional .topupRequest.payloadBody payload = 2;</code>
     */
    public boolean hasPayload() {
      return payloadBuilder_ != null || payload_ != null;
    }
    /**
     * <code>optional .topupRequest.payloadBody payload = 2;</code>
     */
    public com.mh.flux.api.topupRequest.payloadBody getPayload() {
      if (payloadBuilder_ == null) {
        return payload_ == null ? com.mh.flux.api.topupRequest.payloadBody.getDefaultInstance() : payload_;
      } else {
        return payloadBuilder_.getMessage();
      }
    }
    /**
     * <code>optional .topupRequest.payloadBody payload = 2;</code>
     */
    public Builder setPayload(com.mh.flux.api.topupRequest.payloadBody value) {
      if (payloadBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        payload_ = value;
        onChanged();
      } else {
        payloadBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>optional .topupRequest.payloadBody payload = 2;</code>
     */
    public Builder setPayload(
        com.mh.flux.api.topupRequest.payloadBody.Builder builderForValue) {
      if (payloadBuilder_ == null) {
        payload_ = builderForValue.build();
        onChanged();
      } else {
        payloadBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>optional .topupRequest.payloadBody payload = 2;</code>
     */
    public Builder mergePayload(com.mh.flux.api.topupRequest.payloadBody value) {
      if (payloadBuilder_ == null) {
        if (payload_ != null) {
          payload_ =
            com.mh.flux.api.topupRequest.payloadBody.newBuilder(payload_).mergeFrom(value).buildPartial();
        } else {
          payload_ = value;
        }
        onChanged();
      } else {
        payloadBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>optional .topupRequest.payloadBody payload = 2;</code>
     */
    public Builder clearPayload() {
      if (payloadBuilder_ == null) {
        payload_ = null;
        onChanged();
      } else {
        payload_ = null;
        payloadBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>optional .topupRequest.payloadBody payload = 2;</code>
     */
    public com.mh.flux.api.topupRequest.payloadBody.Builder getPayloadBuilder() {
      
      onChanged();
      return getPayloadFieldBuilder().getBuilder();
    }
    /**
     * <code>optional .topupRequest.payloadBody payload = 2;</code>
     */
    public com.mh.flux.api.topupRequest.payloadBodyOrBuilder getPayloadOrBuilder() {
      if (payloadBuilder_ != null) {
        return payloadBuilder_.getMessageOrBuilder();
      } else {
        return payload_ == null ?
            com.mh.flux.api.topupRequest.payloadBody.getDefaultInstance() : payload_;
      }
    }
    /**
     * <code>optional .topupRequest.payloadBody payload = 2;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.mh.flux.api.topupRequest.payloadBody, com.mh.flux.api.topupRequest.payloadBody.Builder, com.mh.flux.api.topupRequest.payloadBodyOrBuilder> 
        getPayloadFieldBuilder() {
      if (payloadBuilder_ == null) {
        payloadBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.mh.flux.api.topupRequest.payloadBody, com.mh.flux.api.topupRequest.payloadBody.Builder, com.mh.flux.api.topupRequest.payloadBodyOrBuilder>(
                getPayload(),
                getParentForChildren(),
                isClean());
        payload_ = null;
      }
      return payloadBuilder_;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }


    // @@protoc_insertion_point(builder_scope:topupRequest)
  }

  // @@protoc_insertion_point(class_scope:topupRequest)
  private static final com.mh.flux.api.topupRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.mh.flux.api.topupRequest();
  }

  public static com.mh.flux.api.topupRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<topupRequest>
      PARSER = new com.google.protobuf.AbstractParser<topupRequest>() {
    public topupRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
        return new topupRequest(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<topupRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<topupRequest> getParserForType() {
    return PARSER;
  }

  public com.mh.flux.api.topupRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

