// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: commonRequestHeader.proto

package com.mh.flux.api.request;

public final class FluxAPIProto {
  private FluxAPIProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_reqHeader_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_reqHeader_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\031commonRequestHeader.proto\"Z\n\treqHeader" +
      "\022\021\n\ttimestamp\030\001 \001(\t\022\020\n\010identity\030\002 \001(\t\022\032\n" +
      "\004type\030\003 \001(\0162\014.messageType\022\014\n\004sign\030\004 \001(\t*" +
      "+\n\013messageType\022\010\n\004JSON\020\000\022\007\n\003XML\020\001\022\t\n\005PRO" +
      "TO\020\002B0\n\027com.mh.flux.api.requestB\014FluxAPI" +
      "ProtoP\001\242\002\004FLUXb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_reqHeader_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_reqHeader_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_reqHeader_descriptor,
        new java.lang.String[] { "Timestamp", "Identity", "Type", "Sign", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
