// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: commonRequestHeader.proto

package com.mh.flux.api.request;

/**
 * Protobuf enum {@code messageType}
 */
public enum messageType
    implements com.google.protobuf.ProtocolMessageEnum {
  /**
   * <code>JSON = 0;</code>
   */
  JSON(0),
  /**
   * <code>XML = 1;</code>
   */
  XML(1),
  /**
   * <code>PROTO = 2;</code>
   */
  PROTO(2),
  UNRECOGNIZED(-1),
  ;

  /**
   * <code>JSON = 0;</code>
   */
  public static final int JSON_VALUE = 0;
  /**
   * <code>XML = 1;</code>
   */
  public static final int XML_VALUE = 1;
  /**
   * <code>PROTO = 2;</code>
   */
  public static final int PROTO_VALUE = 2;


  public final int getNumber() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalArgumentException(
          "Can't get the number of an unknown enum value.");
    }
    return value;
  }

  /**
   * @deprecated Use {@link #forNumber(int)} instead.
   */
  @java.lang.Deprecated
  public static messageType valueOf(int value) {
    return forNumber(value);
  }

  public static messageType forNumber(int value) {
    switch (value) {
      case 0: return JSON;
      case 1: return XML;
      case 2: return PROTO;
      default: return null;
    }
  }

  public static com.google.protobuf.Internal.EnumLiteMap<messageType>
      internalGetValueMap() {
    return internalValueMap;
  }
  private static final com.google.protobuf.Internal.EnumLiteMap<
      messageType> internalValueMap =
        new com.google.protobuf.Internal.EnumLiteMap<messageType>() {
          public messageType findValueByNumber(int number) {
            return messageType.forNumber(number);
          }
        };

  public final com.google.protobuf.Descriptors.EnumValueDescriptor
      getValueDescriptor() {
    return getDescriptor().getValues().get(ordinal());
  }
  public final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptorForType() {
    return getDescriptor();
  }
  public static final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptor() {
    return com.mh.flux.api.request.FluxAPIProto.getDescriptor()
        .getEnumTypes().get(0);
  }

  private static final messageType[] VALUES = values();

  public static messageType valueOf(
      com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
    if (desc.getType() != getDescriptor()) {
      throw new java.lang.IllegalArgumentException(
        "EnumValueDescriptor is not for this type.");
    }
    if (desc.getIndex() == -1) {
      return UNRECOGNIZED;
    }
    return VALUES[desc.getIndex()];
  }

  private final int value;

  private messageType(int value) {
    this.value = value;
  }

  // @@protoc_insertion_point(enum_scope:messageType)
}

