// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: commonRequestHeader.proto

package com.mh.flux.api.request;

public interface reqHeaderOrBuilder extends
    // @@protoc_insertion_point(interface_extends:reqHeader)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional string timestamp = 1;</code>
   */
  java.lang.String getTimestamp();
  /**
   * <code>optional string timestamp = 1;</code>
   */
  com.google.protobuf.ByteString
      getTimestampBytes();

  /**
   * <code>optional string identity = 2;</code>
   */
  java.lang.String getIdentity();
  /**
   * <code>optional string identity = 2;</code>
   */
  com.google.protobuf.ByteString
      getIdentityBytes();

  /**
   * <code>optional .messageType type = 3;</code>
   */
  int getTypeValue();
  /**
   * <code>optional .messageType type = 3;</code>
   */
  com.mh.flux.api.request.messageType getType();

  /**
   * <code>optional string sign = 4;</code>
   */
  java.lang.String getSign();
  /**
   * <code>optional string sign = 4;</code>
   */
  com.google.protobuf.ByteString
      getSignBytes();
}
