// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: commonResponseHeader.proto

package com.mh.flux.api.response;

public final class FluxAPIProto {
  private FluxAPIProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_respHeader_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_respHeader_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\032commonResponseHeader.proto\"-\n\nrespHead" +
      "er\022\017\n\007errcode\030\001 \001(\005\022\016\n\006errmsg\030\002 \001(\tB1\n\030c" +
      "om.mh.flux.api.responseB\014FluxAPIProtoP\001\242" +
      "\002\004FLUXb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_respHeader_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_respHeader_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_respHeader_descriptor,
        new java.lang.String[] { "Errcode", "Errmsg", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
