// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: commonResponseHeader.proto

package com.mh.flux.api.response;

/**
 * Protobuf type {@code respHeader}
 */
public  final class respHeader extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:respHeader)
    respHeaderOrBuilder {
  // Use respHeader.newBuilder() to construct.
  private respHeader(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private respHeader() {
    errcode_ = 0;
    errmsg_ = "";
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
  }
  private respHeader(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    int mutable_bitField0_ = 0;
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!input.skipField(tag)) {
              done = true;
            }
            break;
          }
          case 8: {

            errcode_ = input.readInt32();
            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();

            errmsg_ = s;
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.mh.flux.api.response.FluxAPIProto.internal_static_respHeader_descriptor;
  }

  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.mh.flux.api.response.FluxAPIProto.internal_static_respHeader_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.mh.flux.api.response.respHeader.class, com.mh.flux.api.response.respHeader.Builder.class);
  }

  public static final int ERRCODE_FIELD_NUMBER = 1;
  private int errcode_;
  /**
   * <code>optional int32 errcode = 1;</code>
   */
  public int getErrcode() {
    return errcode_;
  }

  public static final int ERRMSG_FIELD_NUMBER = 2;
  private volatile java.lang.Object errmsg_;
  /**
   * <code>optional string errmsg = 2;</code>
   */
  public java.lang.String getErrmsg() {
    java.lang.Object ref = errmsg_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      errmsg_ = s;
      return s;
    }
  }
  /**
   * <code>optional string errmsg = 2;</code>
   */
  public com.google.protobuf.ByteString
      getErrmsgBytes() {
    java.lang.Object ref = errmsg_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      errmsg_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (errcode_ != 0) {
      output.writeInt32(1, errcode_);
    }
    if (!getErrmsgBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, errmsg_);
    }
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (errcode_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(1, errcode_);
    }
    if (!getErrmsgBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, errmsg_);
    }
    memoizedSize = size;
    return size;
  }

  private static final long serialVersionUID = 0L;
  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.mh.flux.api.response.respHeader)) {
      return super.equals(obj);
    }
    com.mh.flux.api.response.respHeader other = (com.mh.flux.api.response.respHeader) obj;

    boolean result = true;
    result = result && (getErrcode()
        == other.getErrcode());
    result = result && getErrmsg()
        .equals(other.getErrmsg());
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptorForType().hashCode();
    hash = (37 * hash) + ERRCODE_FIELD_NUMBER;
    hash = (53 * hash) + getErrcode();
    hash = (37 * hash) + ERRMSG_FIELD_NUMBER;
    hash = (53 * hash) + getErrmsg().hashCode();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.mh.flux.api.response.respHeader parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.mh.flux.api.response.respHeader parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.mh.flux.api.response.respHeader parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.mh.flux.api.response.respHeader parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.mh.flux.api.response.respHeader parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.mh.flux.api.response.respHeader parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.mh.flux.api.response.respHeader parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.mh.flux.api.response.respHeader parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.mh.flux.api.response.respHeader parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.mh.flux.api.response.respHeader parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.mh.flux.api.response.respHeader prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code respHeader}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:respHeader)
      com.mh.flux.api.response.respHeaderOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.mh.flux.api.response.FluxAPIProto.internal_static_respHeader_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.mh.flux.api.response.FluxAPIProto.internal_static_respHeader_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.mh.flux.api.response.respHeader.class, com.mh.flux.api.response.respHeader.Builder.class);
    }

    // Construct using com.mh.flux.api.response.respHeader.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    public Builder clear() {
      super.clear();
      errcode_ = 0;

      errmsg_ = "";

      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.mh.flux.api.response.FluxAPIProto.internal_static_respHeader_descriptor;
    }

    public com.mh.flux.api.response.respHeader getDefaultInstanceForType() {
      return com.mh.flux.api.response.respHeader.getDefaultInstance();
    }

    public com.mh.flux.api.response.respHeader build() {
      com.mh.flux.api.response.respHeader result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public com.mh.flux.api.response.respHeader buildPartial() {
      com.mh.flux.api.response.respHeader result = new com.mh.flux.api.response.respHeader(this);
      result.errcode_ = errcode_;
      result.errmsg_ = errmsg_;
      onBuilt();
      return result;
    }

    public Builder clone() {
      return (Builder) super.clone();
    }
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.setField(field, value);
    }
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.mh.flux.api.response.respHeader) {
        return mergeFrom((com.mh.flux.api.response.respHeader)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.mh.flux.api.response.respHeader other) {
      if (other == com.mh.flux.api.response.respHeader.getDefaultInstance()) return this;
      if (other.getErrcode() != 0) {
        setErrcode(other.getErrcode());
      }
      if (!other.getErrmsg().isEmpty()) {
        errmsg_ = other.errmsg_;
        onChanged();
      }
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.mh.flux.api.response.respHeader parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.mh.flux.api.response.respHeader) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private int errcode_ ;
    /**
     * <code>optional int32 errcode = 1;</code>
     */
    public int getErrcode() {
      return errcode_;
    }
    /**
     * <code>optional int32 errcode = 1;</code>
     */
    public Builder setErrcode(int value) {
      
      errcode_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional int32 errcode = 1;</code>
     */
    public Builder clearErrcode() {
      
      errcode_ = 0;
      onChanged();
      return this;
    }

    private java.lang.Object errmsg_ = "";
    /**
     * <code>optional string errmsg = 2;</code>
     */
    public java.lang.String getErrmsg() {
      java.lang.Object ref = errmsg_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        errmsg_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>optional string errmsg = 2;</code>
     */
    public com.google.protobuf.ByteString
        getErrmsgBytes() {
      java.lang.Object ref = errmsg_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        errmsg_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string errmsg = 2;</code>
     */
    public Builder setErrmsg(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      errmsg_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional string errmsg = 2;</code>
     */
    public Builder clearErrmsg() {
      
      errmsg_ = getDefaultInstance().getErrmsg();
      onChanged();
      return this;
    }
    /**
     * <code>optional string errmsg = 2;</code>
     */
    public Builder setErrmsgBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      errmsg_ = value;
      onChanged();
      return this;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }


    // @@protoc_insertion_point(builder_scope:respHeader)
  }

  // @@protoc_insertion_point(class_scope:respHeader)
  private static final com.mh.flux.api.response.respHeader DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.mh.flux.api.response.respHeader();
  }

  public static com.mh.flux.api.response.respHeader getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<respHeader>
      PARSER = new com.google.protobuf.AbstractParser<respHeader>() {
    public respHeader parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
        return new respHeader(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<respHeader> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<respHeader> getParserForType() {
    return PARSER;
  }

  public com.mh.flux.api.response.respHeader getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

