// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: commonResponseHeader.proto

package com.mh.flux.api.response;

public interface respHeaderOrBuilder extends
    // @@protoc_insertion_point(interface_extends:respHeader)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional int32 errcode = 1;</code>
   */
  int getErrcode();

  /**
   * <code>optional string errmsg = 2;</code>
   */
  java.lang.String getErrmsg();
  /**
   * <code>optional string errmsg = 2;</code>
   */
  com.google.protobuf.ByteString
      getErrmsgBytes();
}
